#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrafficControl.GUI.Resource", IsApplication=true)]

namespace TrafficControl.GUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TrafficControl.BLL.Resource.String.ApplicationName = global::TrafficControl.GUI.Resource.String.ApplicationName;
			global::TrafficControl.BLL.Resource.String.Hello = global::TrafficControl.GUI.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int UserTypes = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000c
			public const int CaseClosed = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int CaseOpen = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int CaseTaken = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int ColorStrHansen1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ColorStrHansen2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ColorStrHansen3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ColorStrHansen4 = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int ForeGround = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int Grey = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int Red = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int WeakColorStrHansen1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int WeakColorStrHansen2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int WeakColorStrHansen3 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int WeakColorStrHansen4 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int WhiteStrHansen = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int trafficcontrolgreen_color = 2131034127;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_trafficcontrol = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_trafficcontrol = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_trafficcontrol = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_trafficcontrol = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_trafficcontrol = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_trafficcontrol = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_trafficcontrol = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_trafficcontrol = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_pressed_trafficcontrol = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_trafficcontrol = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_trafficcontrol = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_trafficcontrol = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CaseItemSelector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int edittext_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int list_focused_trafficcontrol = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int list_pressed_trafficcontrol = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Logo2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int menu_dropdown_panel_trafficcontrol = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_bg_trafficcontrol = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_horizontal_trafficcontrol = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_primary_trafficcontrol = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_secondary_trafficcontrol = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int selectable_background_trafficcontrol = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SideMenuItemSelector = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner_ab_default_trafficcontrol = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_ab_disabled_trafficcontrol = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_focused_trafficcontrol = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_pressed_trafficcontrol = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_background_ab_trafficcontrol = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_indicator_ab_trafficcontrol = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_selected_focused_trafficcontrol = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_selected_pressed_trafficcontrol = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_trafficcontrol = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_unselected_focused_trafficcontrol = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_unselected_pressed_trafficcontrol = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_trafficcontrol = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int TCLogo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int TCLogoGreen = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int TCLogoRed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int TCLogoYellow = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int trafficcontrolgreen_activated_background_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int trafficcontrolgreen_btn_check_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int trafficcontrolgreen_btn_check_off_disabled_focused_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int trafficcontrolgreen_btn_check_off_disabled_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int trafficcontrolgreen_btn_check_off_focused_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int trafficcontrolgreen_btn_check_off_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int trafficcontrolgreen_btn_check_off_pressed_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int trafficcontrolgreen_btn_check_on_disabled_focused_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int trafficcontrolgreen_btn_check_on_disabled_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int trafficcontrolgreen_btn_check_on_focused_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int trafficcontrolgreen_btn_check_on_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int trafficcontrolgreen_btn_check_on_pressed_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int trafficcontrolgreen_btn_radio_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int trafficcontrolgreen_btn_radio_off_disabled_focused_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int trafficcontrolgreen_btn_radio_off_disabled_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int trafficcontrolgreen_btn_radio_off_focused_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int trafficcontrolgreen_btn_radio_off_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int trafficcontrolgreen_btn_radio_off_pressed_holo_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int trafficcontrolgreen_btn_radio_on_disabled_focused_holo_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int trafficcontrolgreen_btn_radio_on_disabled_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int trafficcontrolgreen_btn_radio_on_focused_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int trafficcontrolgreen_btn_radio_on_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int trafficcontrolgreen_btn_radio_on_pressed_holo_light = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int trafficcontrolgreen_edit_text_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int trafficcontrolgreen_item_background_holo_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int trafficcontrolgreen_list_activated_holo = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int trafficcontrolgreen_list_focused_holo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int trafficcontrolgreen_list_longpressed_holo = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int trafficcontrolgreen_list_pressed_holo_light = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int trafficcontrolgreen_list_selector_background_transition_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int trafficcontrolgreen_list_selector_disabled_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int trafficcontrolgreen_list_selector_holo_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int trafficcontrolgreen_spinner_background_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int trafficcontrolgreen_spinner_default_holo_light = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int trafficcontrolgreen_spinner_disabled_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int trafficcontrolgreen_spinner_focused_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int trafficcontrolgreen_spinner_pressed_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int trafficcontrolgreen_switch_bg_disabled_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int trafficcontrolgreen_switch_bg_focused_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int trafficcontrolgreen_switch_bg_holo_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int trafficcontrolgreen_switch_inner_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int trafficcontrolgreen_switch_thumb_activated_holo_light = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int trafficcontrolgreen_switch_thumb_disabled_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int trafficcontrolgreen_switch_thumb_holo_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int trafficcontrolgreen_switch_thumb_pressed_holo_light = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int trafficcontrolgreen_switch_track_holo_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int trafficcontrolgreen_textfield_activated_holo_light = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int trafficcontrolgreen_textfield_default_holo_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int trafficcontrolgreen_textfield_disabled_focused_holo_light = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int trafficcontrolgreen_textfield_disabled_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int trafficcontrolgreen_textfield_focused_holo_light = 2130837596;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int CaseIcon = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int CaseListing = 2131296260;
			
			// aapt resource value: 0x7f090007
			public const int ConfirmPasswordCreate = 2131296263;
			
			// aapt resource value: 0x7f090016
			public const int ContentFrame = 2131296278;
			
			// aapt resource value: 0x7f090005
			public const int CreateEmailInput = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int CreateFirstNameInput = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int CreateLastNameInput = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int CreatePhonenumberInput = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int CreateUserBtn = 2131296268;
			
			// aapt resource value: 0x7f090012
			public const int EmailInput = 2131296274;
			
			// aapt resource value: 0x7f09000e
			public const int HomeContentFrame = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int LeftListView = 2131296271;
			
			// aapt resource value: 0x7f090015
			public const int LogInErrorMsg = 2131296277;
			
			// aapt resource value: 0x7f090011
			public const int LoginLogo = 2131296273;
			
			// aapt resource value: 0x7f090019
			public const int Menu_About = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int Menu_LogOut = 2131296282;
			
			// aapt resource value: 0x7f090018
			public const int Menu_Options = 2131296280;
			
			// aapt resource value: 0x7f090014
			public const int MyButton = 2131296276;
			
			// aapt resource value: 0x7f09000d
			public const int OptionsDrawer = 2131296269;
			
			// aapt resource value: 0x7f090006
			public const int PasswordCreate = 2131296262;
			
			// aapt resource value: 0x7f090013
			public const int PasswordInput = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int SettingsContentFrame = 2131296279;
			
			// aapt resource value: 0x7f09000b
			public const int UserTypeSpinner = 2131296267;
			
			// aapt resource value: 0x7f090002
			public const int case_id = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int case_name = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int case_time = 2131296259;
			
			// aapt resource value: 0x7f090010
			public const int main_content = 2131296272;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaseItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CasesFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateUser = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LogIn = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MenuActivityLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SettingsFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SideMenuItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UserTypeDropDownItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int UserTypeSpinnerItem = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int CreateUserType = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int settings_create_user = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ActionBar_Solid_Trafficcontrol = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ActionBar_Transparent_Trafficcontrol = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int ActionBarTabStyle_Trafficcontrol = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int ActionButton_CloseMode_Trafficcontrol = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int DropDownListView_Trafficcontrol = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int DropDownNav_Trafficcontrol = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int PopupMenu_Trafficcontrol = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int ProgressBar_Trafficcontrol = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int SpinnerTrafficControlGreen = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Trafficcontrol = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int Theme_Trafficcontrol_Widget = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int TrafficControlGreen = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int _TrafficControlGreen = 2131165196;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
