#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrafficControl.GUI.Resource", IsApplication=true)]

namespace TrafficControl.GUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TrafficControl.BLL.Resource.String.ApplicationName = global::TrafficControl.GUI.Resource.String.ApplicationName;
			global::TrafficControl.BLL.Resource.String.Hello = global::TrafficControl.GUI.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000c
			public const int CaseClosed = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int CaseOpen = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int CaseTaken = 2131034125;
			
			// aapt resource value: 0x7f050001
			public const int ColorStrHansen1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ColorStrHansen2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ColorStrHansen3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ColorStrHansen4 = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int ForeGround = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Red = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int WeakColorStrHansen1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int WeakColorStrHansen2 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int WeakColorStrHansen3 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int WeakColorStrHansen4 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int WhiteStrHansen = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int trafficcontrolgreen_color = 2131034126;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_trafficcontrol = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_trafficcontrol = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_trafficcontrol = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_trafficcontrol = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_trafficcontrol = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_trafficcontrol = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_trafficcontrol = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_trafficcontrol = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_pressed_trafficcontrol = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_trafficcontrol = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_trafficcontrol = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_trafficcontrol = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int edittext_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int list_focused_trafficcontrol = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int list_pressed_trafficcontrol = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Logo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Logo2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menu_dropdown_panel_trafficcontrol = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progress_bg_trafficcontrol = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progress_horizontal_trafficcontrol = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int progress_primary_trafficcontrol = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_secondary_trafficcontrol = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int selectable_background_trafficcontrol = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int spinner_ab_default_trafficcontrol = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int spinner_ab_disabled_trafficcontrol = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int spinner_ab_focused_trafficcontrol = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_ab_pressed_trafficcontrol = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_background_ab_trafficcontrol = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int tab_indicator_ab_trafficcontrol = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tab_selected_focused_trafficcontrol = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_selected_pressed_trafficcontrol = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_selected_trafficcontrol = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_unselected_focused_trafficcontrol = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_unselected_pressed_trafficcontrol = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_unselected_trafficcontrol = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int TCLogo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int TCLogoGreen = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int TCLogoRed = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int TCLogoYellow = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int trafficcontrolgreen_btn_check_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int trafficcontrolgreen_btn_check_off_disabled_focused_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int trafficcontrolgreen_btn_check_off_disabled_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int trafficcontrolgreen_btn_check_off_focused_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int trafficcontrolgreen_btn_check_off_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int trafficcontrolgreen_btn_check_off_pressed_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int trafficcontrolgreen_btn_check_on_disabled_focused_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int trafficcontrolgreen_btn_check_on_disabled_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int trafficcontrolgreen_btn_check_on_focused_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int trafficcontrolgreen_btn_check_on_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int trafficcontrolgreen_btn_check_on_pressed_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int trafficcontrolgreen_btn_radio_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int trafficcontrolgreen_btn_radio_off_disabled_focused_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int trafficcontrolgreen_btn_radio_off_disabled_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int trafficcontrolgreen_btn_radio_off_focused_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int trafficcontrolgreen_btn_radio_off_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int trafficcontrolgreen_btn_radio_off_pressed_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int trafficcontrolgreen_btn_radio_on_disabled_focused_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int trafficcontrolgreen_btn_radio_on_disabled_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int trafficcontrolgreen_btn_radio_on_focused_holo_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int trafficcontrolgreen_btn_radio_on_holo_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int trafficcontrolgreen_btn_radio_on_pressed_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int trafficcontrolgreen_edit_text_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int trafficcontrolgreen_textfield_activated_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int trafficcontrolgreen_textfield_default_holo_light = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int trafficcontrolgreen_textfield_disabled_focused_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int trafficcontrolgreen_textfield_disabled_holo_light = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int trafficcontrolgreen_textfield_focused_holo_light = 2130837571;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int About = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int AllCasesListing = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int CaseIcon = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int EmailInput = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int LeftListView = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int LogInErrorMsg = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int LoginLogo = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int MyButton = 2131230730;
			
			// aapt resource value: 0x7f080004
			public const int MyCasesListing = 2131230724;
			
			// aapt resource value: 0x7f080010
			public const int Options = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int OptionsContentFrame = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int OptionsDrawer = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int PasswordInput = 2131230729;
			
			// aapt resource value: 0x7f08000f
			public const int Profile = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int case_id = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int case_name = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int main_content = 2131230726;
			
			// aapt resource value: 0x7f080003
			public const int textView1 = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CaseItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LogIn = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Options = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Trafficcontrol = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Transparent_Trafficcontrol = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ActionBarTabStyle_Trafficcontrol = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionButton_CloseMode_Trafficcontrol = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int DropDownListView_Trafficcontrol = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DropDownNav_Trafficcontrol = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PopupMenu_Trafficcontrol = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ProgressBar_Trafficcontrol = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Trafficcontrol = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Theme_Trafficcontrol_Widget = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int TrafficControlGreen = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int _TrafficControlGreen = 2131099659;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
